#*** Traffic Classification Config for nmeta
#*** Written in YAML
#
#*** max bytes of new flow packets to send to controller:
miss_send_len: 1500
#
#*** Tell switch how to handle fragments (see OpenFlow spec)
ofpc_frag: 0
#
#========== SYSLOG ==================================
#*** Set to 1 if want to log to syslog:
syslog_enabled: 1
#
#*** Where to send syslog (use localhost to keep on-box):
loghost: localhost
#
#*** Port number to send on:
logport: 514
#
#*** Facility to use:
logfacility: 19
#
#*** Syslog Log Format:
syslog_format: "sev=%(levelname)s module=%(name)s func=%(funcName)s %(message)s"
#
#*** Syslog Logging Levels Per Module
#*** Values can be one of CRITICAL|ERROR|WARNING|INFO|DEBUG:
nmeta_logging_level_s: INFO
flow_logging_level_s: INFO
qos_logging_level_s: INFO
tc_policy_logging_level_s: INFO
tc_static_logging_level_s: INFO
tc_identity_logging_level_s: INFO
tc_payload_logging_level_s: INFO
tc_statistical_logging_level_s: INFO
ca_logging_level_s: INFO
measure_logging_level_s: INFO
forwarding_logging_level_s: INFO
api_logging_level_s: INFO
#
#========== CONSOLE LOGGING =========================
#*** Set to 1 if want to log to console:
console_log_enabled: 1
#
#*** Console Log Format:
console_format: "%(levelname)s: %(name)s %(funcName)s: %(message)s"
#
#*** Console Logging Levels Per Module
#*** Values can be one of CRITICAL|ERROR|WARNING|INFO|DEBUG:
nmeta_logging_level_c: INFO
flow_logging_level_c: INFO
qos_logging_level_c: INFO
tc_policy_logging_level_c: INFO
tc_static_logging_level_c: INFO
tc_identity_logging_level_c: DEBUG
tc_payload_logging_level_c: INFO
tc_statistical_logging_level_c: INFO
ca_logging_level_c: INFO
measure_logging_level_c: INFO
forwarding_logging_level_c: INFO
api_logging_level_c: INFO
#
#========== TABLE MAINTENANCE SETTINGS ==============
#*** Flow Metadata Table entry maximum age in seconds
#*** before being eligible for removal:
fm_table_max_age: 600
#
#*** Flow Metadata Table interval in seconds between
#*** running the tidy-up process that removes old
#*** entries:
fm_table_tidyup_interval: 30
#
#*** Identity NIC Table entry maximum age in seconds
#*** before being eligible for removal:
identity_nic_table_max_age: 600
#
#*** Identity NIC System entry maximum age in seconds
#*** before being eligible for removal:
identity_system_table_max_age: 600
#
#*** Identity NIC and System Tables interval in seconds between
#*** running the tidy-up process that removes old
#*** entries:
identity_table_tidyup_interval: 234
#
#*** Max age in seconds for a learnt ARP before considering for deletion
#*** and ignoring for identity purposes:
identity_arp_max_age: 60

#*** Statistical Flow Classification in Progress (FCIP) table entry
#*** maximum age in seconds before being eligible for removal:
statistical_fcip_table_max_age: 600
#
#*** Statistical Flow Classification in Progress (FCIP) table interval
#*** in seconds between running the tidy-up process that removes old
#*** entries:
statistical_fcip_table_tidyup_interval: 45
#
#*** Payload Flow Classification in Progress (FCIP) table entry
#*** maximum age in seconds before being eligible for removal:
payload_fcip_table_max_age: 600
#
#*** Payload Flow Classification in Progress (FCIP) table interval
#*** in seconds between running the tidy-up process that removes old
#*** entries:
payload_fcip_table_tidyup_interval: 40
#
#*** Measure buckets
#*** maximum age in seconds before being eligible for removal:
measure_buckets_max_age: 600
#
#*** Measure buckets interval
#*** in seconds between running the tidy-up process that removes old
#*** buckets:
measure_buckets_tidyup_interval: 321
#
#========== MEASUREMENT =============================
#*** Control how measurements are made regarding
#*** nmeta performance etc.
#
#*** Number of preceding seconds that events are averaged over:
event_rate_interval: 60
#
#========== FLOW METADATA =============================
# Turn this on to augment flow metadata table with identity metadata:
augment_flow_metadata_with_identity: 1
